<?php

namespace AppBundle\Repository;

/**
 * HermanoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HermanoRepository extends \Doctrine\ORM\EntityRepository
{
}
