<?php

namespace AppBundle\Repository;

/**
 * PrivilegioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivilegioRepository extends \Doctrine\ORM\EntityRepository
{
}
